"""Resolution and convergence diagnostics for Phase-1 sigma curves.

This module is simulator-independent. It operates on the top-level request
ledgers already generated by the white-box atlas and uses the same event
semantics as ``atlas_analysis.py``. It does not smooth sigma and it never treats
horizon samples as independent Monte Carlo observations.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from math import sqrt
from pathlib import Path

import numpy as np
import pandas as pd

from atlas_analysis import (
    FirstViolationObservation,
    calculate_first_violation_observation_for_trajectory,
)
from generate_sigma_plots import (
    select_best_sigma_representative_regions_for_one_physical_setting,
)


def reconstruct_first_violation_observations_for_region(
    physical_setting_request_ledger: pd.DataFrame,
    representative_region: pd.Series,
    stop_time: float,
) -> list[tuple[object, FirstViolationObservation]]:
    """Reconstruct one first-violation observation per independent trajectory.

    Args:
        physical_setting_request_ledger: All request rows for one physical setting.
        representative_region: One selected admissibility-region row.
        stop_time: Common simulator stop time.

    Returns:
        Ordered ``(trajectory_id, FirstViolationObservation)`` pairs.

    Called by:
        - ``calculate_sigma_resolution_diagnostics_for_region`` in this module.
        - ``test_primary_no_violation_semantics_matches_first_event_form`` in
          ``test_sigma_curve_diagnostics.py``.
    """
    observations: list[tuple[object, FirstViolationObservation]] = []
    for trajectory_id, trajectory_ledger in physical_setting_request_ledger.groupby(
        "trajectory", sort=True
    ):
        observation = calculate_first_violation_observation_for_trajectory(
            trajectory_request_ledger=trajectory_ledger,
            latency_threshold=float(representative_region["l_max"]),
            cost_threshold=float(representative_region["c_max"]),
            quality_threshold=float(representative_region["q_min"]),
            stop_time=float(stop_time),
        )
        observations.append((trajectory_id, observation))
    if not observations:
        raise ValueError("at least one trajectory is required")
    return observations


def calculate_no_violation_probability_through_horizon(
    observations: list[FirstViolationObservation],
    horizon: float,
) -> float:
    """Estimate the primary cumulative event: no A violation anywhere through H.

    The event is ``no violation of A occurs at any time t <= H``. Under the
    event-driven simulator semantics this is exactly equivalent to asking that
    the first actual violation time is strictly greater than H.

    Args:
        observations: One first-violation observation per independent trajectory.
        horizon: Horizon H at which cumulative admissibility is evaluated.

    Returns:
        Empirical probability of no violation through H.

    Called by:
        - ``calculate_exact_first_crossing_below_target`` in this module.
        - ``calculate_split_half_curve_distance`` in this module.
        - ``calculate_sigma_resolution_diagnostics_for_region`` in this module.
        - semantic regression tests in ``test_sigma_curve_diagnostics.py``.
    """
    if not observations:
        raise ValueError("observations must be non-empty")
    h = float(horizon)
    if h < 0.0:
        raise ValueError("horizon must be non-negative")
    survived = [
        observation.time is None or float(observation.time) > h
        for observation in observations
    ]
    return float(np.mean(survived))


def calculate_exact_first_crossing_below_target(
    observations: list[FirstViolationObservation],
    target_survival: float,
    stop_time: float,
) -> float | None:
    """Return the exact event time where empirical sigma first falls below target.

    No reporting horizon grid is used. With the strict cumulative convention,
    a violation occurring exactly at H counts as a violation by H, so the curve
    value immediately after processing all events at that time is used.

    Args:
        observations: One first-violation observation per independent trajectory.
        target_survival: Target survival in ``(0,1)``.
        stop_time: Largest observable horizon.

    Returns:
        Exact first event time where sigma is below target, or ``None`` if the
        target is not crossed by ``stop_time``.

    Called by:
        - ``calculate_sigma_resolution_diagnostics_for_region`` in this module.
        - ``test_exact_crossing_uses_event_time_not_reporting_grid`` in
          ``test_sigma_curve_diagnostics.py``.
        - Future scientific Phase-1 reference-search code.
    """
    target = float(target_survival)
    stop = float(stop_time)
    if not 0.0 < target < 1.0:
        raise ValueError("target_survival must lie strictly between 0 and 1")
    event_times = sorted(
        {
            float(observation.time)
            for observation in observations
            if observation.time is not None
            and 0.0 <= float(observation.time) <= stop
        }
    )
    for event_time in event_times:
        sigma = calculate_no_violation_probability_through_horizon(
            observations, event_time
        )
        if sigma < target:
            return float(event_time)
    return None


def calculate_split_half_curve_distance(
    labeled_observations: list[tuple[object, FirstViolationObservation]],
    anchor_horizon: float,
    stop_time: float,
) -> tuple[float | None, float | None]:
    """Compare deterministic alternating trajectory halves as a stability check.

    Args:
        labeled_observations: Ordered trajectory IDs and observations.
        anchor_horizon: H* for the anchor comparison.
        stop_time: Full observable horizon.

    Returns:
        ``(anchor_absolute_difference, full_curve_supremum_difference)``. Both are
        ``None`` when fewer than two trajectories are available.

    Called by:
        - ``calculate_sigma_resolution_diagnostics_for_region`` in this module.
    """
    if len(labeled_observations) < 2:
        return None, None
    first_half = [obs for index, (_, obs) in enumerate(labeled_observations) if index % 2 == 0]
    second_half = [obs for index, (_, obs) in enumerate(labeled_observations) if index % 2 == 1]
    if not first_half or not second_half:
        return None, None

    anchor_difference = abs(
        calculate_no_violation_probability_through_horizon(first_half, anchor_horizon)
        - calculate_no_violation_probability_through_horizon(second_half, anchor_horizon)
    )
    event_times = {
        0.0,
        float(stop_time),
        *[
            float(obs.time)
            for obs in first_half + second_half
            if obs.time is not None and 0.0 <= float(obs.time) <= float(stop_time)
        ],
    }
    sup_difference = max(
        abs(
            calculate_no_violation_probability_through_horizon(first_half, horizon)
            - calculate_no_violation_probability_through_horizon(second_half, horizon)
        )
        for horizon in sorted(event_times)
    )
    return float(anchor_difference), float(sup_difference)


def calculate_sigma_resolution_diagnostics_for_region(
    physical_setting_request_ledger: pd.DataFrame,
    representative_region: pd.Series,
    anchor_horizon: float,
    target_survival: float,
    stop_time: float,
) -> dict[str, object]:
    """Summarize finite-N resolution and split-half stability of one sigma curve.

    These diagnostics characterize how well the empirical staircase resolves the
    underlying survival function. They are not a smoothing procedure and they do
    not alter the white-box estimator.

    Called by:
        - ``write_best_sigma_curve_diagnostics`` in this module.
        - ``test_resolution_diagnostics_report_expected_jump_size`` in
          ``test_sigma_curve_diagnostics.py``.
    """
    labeled = reconstruct_first_violation_observations_for_region(
        physical_setting_request_ledger,
        representative_region,
        stop_time,
    )
    observations = [observation for _, observation in labeled]
    n_trajectories = len(observations)
    finite_times = [
        float(observation.time)
        for observation in observations
        if observation.time is not None
        and 0.0 <= float(observation.time) <= float(stop_time)
    ]
    event_counts = Counter(finite_times)
    maximum_jump = (
        max(event_counts.values()) / n_trajectories if event_counts else 0.0
    )
    ordered_event_times = sorted(event_counts)
    plateau_boundaries = [0.0, *ordered_event_times, float(stop_time)]
    plateau_lengths = [
        max(0.0, right - left)
        for left, right in zip(plateau_boundaries[:-1], plateau_boundaries[1:])
    ]
    longest_plateau = max(plateau_lengths) if plateau_lengths else float(stop_time)

    sigma_anchor = calculate_no_violation_probability_through_horizon(
        observations, anchor_horizon
    )
    n_failed_by_anchor = sum(
        observation.time is not None and float(observation.time) <= float(anchor_horizon)
        for observation in observations
    )
    anchor_standard_error = sqrt(
        sigma_anchor * (1.0 - sigma_anchor) / n_trajectories
    )
    split_anchor_difference, split_sup_difference = calculate_split_half_curve_distance(
        labeled,
        anchor_horizon=anchor_horizon,
        stop_time=stop_time,
    )

    return {
        "physical_setting_id": str(representative_region["physical_setting_id"]),
        "region_id": str(representative_region["region_id"]),
        "l_max": float(representative_region["l_max"]),
        "c_max": float(representative_region["c_max"]),
        "q_min": float(representative_region["q_min"]),
        "n_trajectories": int(n_trajectories),
        "vertical_probability_resolution": float(1.0 / n_trajectories),
        "sigma_anchor_exact": float(sigma_anchor),
        "n_failed_by_anchor": int(n_failed_by_anchor),
        "anchor_pointwise_binomial_se": float(anchor_standard_error),
        "n_failed_by_stop": int(len(finite_times)),
        "n_unique_first_violation_times": int(len(ordered_event_times)),
        "maximum_empirical_jump": float(maximum_jump),
        "longest_plateau": float(longest_plateau),
        "longest_plateau_fraction_of_domain": float(longest_plateau / float(stop_time)),
        "exact_first_crossing_below_target": calculate_exact_first_crossing_below_target(
            observations,
            target_survival=target_survival,
            stop_time=stop_time,
        ),
        "split_half_anchor_absolute_difference": split_anchor_difference,
        "split_half_curve_supremum_difference": split_sup_difference,
    }


def write_best_sigma_curve_diagnostics(
    results_directory: Path,
    target_survival: float,
) -> pd.DataFrame:
    """Write diagnostics for the same best ARs used by the sigma PNG post-process.

    Args:
        results_directory: Existing Phase-1 atlas result directory.
        target_survival: Target used to select best/bracketing sigma levels.

    Returns:
        Diagnostics table, one row per plotted representative region.

    Side effects:
        Writes ``sigma_plots/sigma_curve_resolution_diagnostics.csv``.

    Called by:
        - ``main`` in this module.
        - end-to-end tests in ``test_sigma_curve_diagnostics.py``.
    """
    representatives = pd.read_csv(results_directory / "representative_regions_by_sigma.csv")
    ledgers = pd.read_csv(results_directory / "all_top_level_request_ledgers.csv")
    configuration = json.loads(
        (results_directory / "effective_config.json").read_text(encoding="utf-8")
    )
    anchor_horizon = float(configuration["admissibility_scan"]["anchor_horizon"])
    stop_time = float(configuration["horizon"]["simulation_stop_time"])

    rows: list[dict[str, object]] = []
    for physical_setting_id, representative_group in representatives.groupby(
        "physical_setting_id", sort=True
    ):
        selected = select_best_sigma_representative_regions_for_one_physical_setting(
            representative_group,
            target_anchor_sigma=target_survival,
        )
        physical_ledger = ledgers[
            ledgers["physical_setting_id"] == physical_setting_id
        ].copy()
        for _, representative_region in selected.iterrows():
            rows.append(
                calculate_sigma_resolution_diagnostics_for_region(
                    physical_setting_request_ledger=physical_ledger,
                    representative_region=representative_region,
                    anchor_horizon=anchor_horizon,
                    target_survival=target_survival,
                    stop_time=stop_time,
                )
            )

    diagnostics = pd.DataFrame(rows)
    output_directory = results_directory / "sigma_plots"
    output_directory.mkdir(parents=True, exist_ok=True)
    diagnostics.to_csv(
        output_directory / "sigma_curve_resolution_diagnostics.csv",
        index=False,
    )
    return diagnostics


def parse_command_line_arguments() -> argparse.Namespace:
    """Parse Phase-1 sigma-diagnostic command-line arguments.

    Called by:
        - ``main`` in this module.
    """
    parser = argparse.ArgumentParser(
        description="Diagnose exact empirical Phase-1 sigma curve resolution."
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("results/development_atlas"),
    )
    parser.add_argument("--target-sigma", type=float, default=0.95)
    return parser.parse_args()


def main() -> None:
    """Write sigma-resolution diagnostics and print an auditable marker.

    Called by:
        - Python ``__main__`` entry point of this module.
    """
    arguments = parse_command_line_arguments()
    diagnostics = write_best_sigma_curve_diagnostics(
        results_directory=arguments.results_dir,
        target_survival=float(arguments.target_sigma),
    )
    print(
        "PHASE1_SIGMA_CURVE_DIAGNOSTICS_PASS",
        f"n_regions={len(diagnostics)}",
        f"output={arguments.results_dir / 'sigma_plots' / 'sigma_curve_resolution_diagnostics.csv'}",
    )


if __name__ == "__main__":
    main()
